#!/usr/bin/env bash
#Bash script that displays messages when read some signals
echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/holbertonscript.pid; exit' SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
done
