#!/usr/bin/env bash
#Creating a script that uses if, else if and else statements
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
	    echo "bad luck"
	elif [ $x -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Holberton School"
	fi
	((x++))
done
